language: node_js
node_js:
- '8'

cache:
  yarn: true
  directories:
    - node_modules

script: yarn run build

after_success:
  - npm i -g now
  - yarn run deploy
  - yarn run alias

branches:
  only:
    - master

notifications:
  email: false
