language: node_js
node_js:
- '8'

cache:
  yarn: true
  directories:
    - node_modules

script: npm run build

after_succes:
  - npm i -g now
  - yarn run deply
  - yarn run alias

branches:
  only:
    - master

notifications:
  email: false
